server:
  port: 8181
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/skylineshop
    username: TrucPham
    password: 12345
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: 1.0.0

