spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skylineshop
    username: TrucPham
    password: 12345
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

application:
  security:
    jwt:
      secret-key : 89dd3a965fddb1460b64c074c928ee19f6697a168bc5ec72c336fb6df64289c4
      expriration : 86400000 # a day
      refresh-token :
        expriration : 604800000 # 7 days

server:
  port: 8181
