server:
  port: 8182
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}?useSSL=false
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Service
    version: 1.0.0
